### ISSUE TITLE
Facebook og:title

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/Seo4Evo#11]
The og:title for Facebook only displays if there is a custom title.
I updated this so it will work either way and added some more options in "install/assets/snippets/Seo4Evo.tpl"
Let me know what you think.

[Seo4Evo.zip](https://github.com/Nicola1971/Seo4Evo/files/1636463/Seo4Evo.zip)

Edit: Should 301 Redirect field be changed to "text" instead of "textareamini"?

**Comment by Nicola1971** [comment]
Thanks i will check tomorrow.

> Edit: Should 301 Redirect field be changed to "text" instead of "textareamini"?

No, because VirtualAlias support multiple old urls and must be added on a separate line

**Comment by Nicola1971** [comment]
just checked the additions. Nice. 👍 
Why don't do a pull request?, so you can result as a contributor.

**Comment by risingisland** [comment]
Pull request submitted 👍

**Comment by Nicola1971** [comment]
merged
