### ISSUE TITLE
Dynamic Description error with PHP 7.2

### ISSUE THREAD

**Issue by leonie12** [Nicola1971/Seo4Evo#14]
When changing PHP version from 7.1 to 7.2 I get this error:

> Error : Use of undefined constant getDynaDescription - assumed 'getDynaDescription' (this will throw an Error in a future version of PHP).

Changing back to 7.1 resolves the error.

**Comment by fourroses666** [comment]
Isn’t that a custom plugin? Don’t think its core

**Comment by leonie12** [comment]
Seems to be custom. Nonetheless this is the plugin's repo and the plugin has an issue with PHP 7.2 …

**Comment by fourroses666** [comment]
Oh sorry thought it was an evolution issue

**Comment by leonie12** [comment]
It seems that replacing in line 121
`if (!function_exists(getDynaDescription)) {`
with
`if (!function_exists('getDynaDescription')) {`
solves the issue.

**Comment by Beeltec** [comment]
You also need to change line 131 in Seo4Evo.tpl from
`$editedon = date(r,$modx->documentObject['editedon']);`
to
`$editedon = date('r',$modx->documentObject['editedon']);`

**Comment by Nicola1971** [comment]
fixed issue upto php 7.4.33
