### ISSUE TITLE
Last modified meta tag

### ISSUE THREAD

**Issue by fourroses666** [Nicola1971/Seo4Evo#6]
You could add last modified meta tag
http://forums.modx.com/thread/96058/adding#dis-post-519914

**Comment by Nicola1971** [comment]
Seo4Evo still include Last modified meta
https://github.com/Nicola1971/Seo4Evo/blob/master/install/assets/snippets/Seo4Evo.tpl#L107

But should be removed in the next version, because it's obsolete in HTML5 doc types and does not validate the markup
