### ISSUE TITLE
Adding google example

### ISSUE THREAD

**Issue by fourroses666** [Nicola1971/Seo4Evo#9]
Hey Nicola, 

Will be great to have an example like Google.
When you add the title and description it also shows it on an example.
This way clients can see how it looks like on Google.

https://jsfiddle.net/fourroses666/2otme73n/

![modx-seo-plugin-google-preview](https://user-images.githubusercontent.com/523389/33041902-3cfe45fa-ce40-11e7-8e8f-3bed5e75692b.png)

**Comment by Nicola1971** [comment]
Yes, looks great.
i will try to add soon.

Seo4evo needs a lot of updates: 
- replace dynamicdescription
- remove outdated seo things 
- structured data (maybe with preview)

Any seo suggestions are welcome

**Comment by fourroses666** [comment]
At the moment no new ideas. (Haven't used the plugin allot.)
Its possible to add a counter to the title and description, but if I'm right you can't save the page when adding too much text. I would like the page to be able to save even if you add too much text.

**Comment by Nicola1971** [comment]
@fourroses666 
https://github.com/Nicola1971/GooglePreviewTv
![googlepreview](https://user-images.githubusercontent.com/7342798/34919936-f344604c-f96a-11e7-8332-475a77b0c03d.png)
